name: Deploy PR Preview
on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set base path for GitHub Pages
        run: |
          echo "BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Build the app
        run: pnpm build
        env:
          DEPLOY_TARGET: github-pages

      - name: Deploy to preview branch
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # or any preview branch
          folder: out        # output folder from `next build`
          clean: true   